# ION supplies this software code for testing purposes only.
# The scope of this software code is exclusively limited to the demonstration
# of the structure of an application using the ION Desktop Bus solution.
#
# ION does not guarantee the correct behavior
# of any deployed application using this software code.
# This software code has not been thoroughly tested under all conditions.
# ION, therefore, cannot guarantee or imply reliability, serviceability,
# or function of this software.
#
# Any use of this software outside of this defined scope is the sole
# responsibility of the user.
#
# For further information please refer to the Terms and Conditions page:
#
# https:#github.com/IONDesktopBus/Terms-and-Conditions

#FROM - Image to start from.

#RUN - Runs a command in the container

#CMD - Command that should be executed when running the image as a container.